<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE student[
    <!ELEMENT student (firstName, lastName, studentId,subjects)>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT lastName (#PCDATA)>
    <!ELEMENT studentId (#PCDATA)>
    <!ELEMENT subjects (subject*)>
    <!ATTLIST subject name CDATA #REQUIRED>
    <!ELEMENT subject (creditPoint,mark,grade)>
    <!ELEMENT creditPoint (#PCDATA)>
    <!ELEMENT mark (#PCDATA)>
    <!ELEMENT grade (#PCDATA)>
]>
<student>
    <firstName>Smith</firstName>
    <lastName>John</lastName>
    <studentId>1231234</studentId>
    <subjects>
        <subject name="MATH101">
            <creditPoint>4</creditPoint>
            <mark>85</mark>
            <grade>A</grade>
        </subject>
        <subject name="ECON111">
            <creditPoint>5</creditPoint>
            <mark>70</mark>
            <grade>B</grade>
        </subject>
        <subject name="CS100">
            <creditPoint>5</creditPoint>
            <mark>80</mark>
            <grade>A</grade>
        </subject>
        <subject name="LAW121">
            <creditPoint>6</creditPoint>
            <mark>75</mark>
            <grade>B</grade>
        </subject>
    </subjects>
</student>