=== sure6/CSIT884/week8/student.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.leesure.com"
            elementFormDefault="qualified">
    <xsd:element name="student">
        <xsd:complexType mixed="true">
            <xsd:sequence>
                <xsd:element name="firstName" type="xsd:string"/>
                <xsd:element name="lastName" type="xsd:string"/>
                <xsd:element name="email" type="xsd:string"/>
                <xsd:element name="mobile" type="xsd:string" default="13111111222"/>
                <xsd:element name="gender" type="xsd:string" fixed="male"/>
                <xsd:element name="age" >
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:integer">
                            <xsd:maxInclusive value="0"/>
                            <xsd:maxInclusive value="90"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="weight" >
                    <xsd:complexType>
                        <xsd:complexContent>
                            <xsd:restriction base="xsd:string">
                                <xsd:attribute name="lang" type="xsd:string"/>
                            </xsd:restriction>
                        </xsd:complexContent>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== sure6/CSIT884/week8/student.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 如果在xsd中不加xmlns 默认的命名空间则下面必须写xmlns -->
<student  xmlns="http://www.leesure.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.leesure.com student.xsd">
    adsad<firstName>lee</firstName>
    <lastName>sure</lastName>
    <email>arm125@qq.com</email>
    <mobile>13525232332</mobile>
    <gender>male</gender>
    <age>0</age>
    <weight lang="EN">10</weight>
</student>
